import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Info from "../components/Info";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Quicky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section>
          <Banner />
        </section>
        {/* TODO: HOW it Works section */}
        <section>
          <Info />
        </section>
        {/* TODO: Customer reviews section */}
      </main>
      {/* TODO: Create footer component */}
      <Footer />
    </div>
  );
}
